//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chaotic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _2560x1440 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _2560x1440() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chaotic.Resources.2560x1440", typeof(_2560x1440).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2330,1225.
        /// </summary>
        internal static string AdventureMenu {
            get {
                return ResourceManager.GetString("AdventureMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1800,570.
        /// </summary>
        internal static string Bifrost1 {
            get {
                return ResourceManager.GetString("Bifrost1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1800,650.
        /// </summary>
        internal static string Bifrost2 {
            get {
                return ResourceManager.GetString("Bifrost2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1800,730.
        /// </summary>
        internal static string Bifrost3 {
            get {
                return ResourceManager.GetString("Bifrost3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1800,860.
        /// </summary>
        internal static string Bifrost4 {
            get {
                return ResourceManager.GetString("Bifrost4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1800,940.
        /// </summary>
        internal static string Bifrost5 {
            get {
                return ResourceManager.GetString("Bifrost5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1800,1025.
        /// </summary>
        internal static string Bifrost6 {
            get {
                return ResourceManager.GetString("Bifrost6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2275,975.
        /// </summary>
        internal static string BifrostMenu {
            get {
                return ResourceManager.GetString("BifrostMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1175,800,100,50.
        /// </summary>
        internal static string BifrostOk_Region {
            get {
                return ResourceManager.GetString("BifrostOk_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400,200,1000,400.
        /// </summary>
        internal static string BossMobHealth_Region {
            get {
                return ResourceManager.GetString("BossMobHealth_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2350,1175,150,75.
        /// </summary>
        internal static string BottomRight_Exit {
            get {
                return ResourceManager.GetString("BottomRight_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1280,700.
        /// </summary>
        internal static string CenterScreen {
            get {
                return ResourceManager.GetString("CenterScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 850,540.
        /// </summary>
        internal static string ChaosDungeon_1415 {
            get {
                return ResourceManager.GetString("ChaosDungeon_1415", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 850,610.
        /// </summary>
        internal static string ChaosDungeon_1445 {
            get {
                return ResourceManager.GetString("ChaosDungeon_1445", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 850,680.
        /// </summary>
        internal static string ChaosDungeon_1475 {
            get {
                return ResourceManager.GetString("ChaosDungeon_1475", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 850,750.
        /// </summary>
        internal static string ChaosDungeon_1490 {
            get {
                return ResourceManager.GetString("ChaosDungeon_1490", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 850,820.
        /// </summary>
        internal static string ChaosDungeon_1520 {
            get {
                return ResourceManager.GetString("ChaosDungeon_1520", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 850,890.
        /// </summary>
        internal static string ChaosDungeon_1540 {
            get {
                return ResourceManager.GetString("ChaosDungeon_1540", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 850,960.
        /// </summary>
        internal static string ChaosDungeon_1560 {
            get {
                return ResourceManager.GetString("ChaosDungeon_1560", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 850,540.
        /// </summary>
        internal static string ChaosDungeon_1580 {
            get {
                return ResourceManager.GetString("ChaosDungeon_1580", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 850,610.
        /// </summary>
        internal static string ChaosDungeon_1600 {
            get {
                return ResourceManager.GetString("ChaosDungeon_1600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 850,540.
        /// </summary>
        internal static string ChaosDungeon_1610 {
            get {
                return ResourceManager.GetString("ChaosDungeon_1610", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1725,420.
        /// </summary>
        internal static string ChaosDungeon_Elgacia {
            get {
                return ResourceManager.GetString("ChaosDungeon_Elgacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2100,420.
        /// </summary>
        internal static string ChaosDungeon_RightArrow {
            get {
                return ResourceManager.GetString("ChaosDungeon_RightArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1175,465.
        /// </summary>
        internal static string ChaosDungeon_Shortcut {
            get {
                return ResourceManager.GetString("ChaosDungeon_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1540,420.
        /// </summary>
        internal static string ChaosDungeon_Vern {
            get {
                return ResourceManager.GetString("ChaosDungeon_Vern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1930,420.
        /// </summary>
        internal static string ChaosDungeon_Voldis {
            get {
                return ResourceManager.GetString("ChaosDungeon_Voldis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,450,250,50.
        /// </summary>
        internal static string ChaosLeave_Region {
            get {
                return ResourceManager.GetString("ChaosLeave_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1200,1100,150,75.
        /// </summary>
        internal static string ChaosOk_Region {
            get {
                return ResourceManager.GetString("ChaosOk_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1200,1115,150,130.
        /// </summary>
        internal static string CharacterIcon_Region {
            get {
                return ResourceManager.GetString("CharacterIcon_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2265,1220.
        /// </summary>
        internal static string CharacterMenu {
            get {
                return ResourceManager.GetString("CharacterMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2200,1130.
        /// </summary>
        internal static string CharacterProfileMenu {
            get {
                return ResourceManager.GetString("CharacterProfileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1020.
        /// </summary>
        internal static string CharSelectCol0 {
            get {
                return ResourceManager.GetString("CharSelectCol0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1285.
        /// </summary>
        internal static string CharSelectCol1 {
            get {
                return ResourceManager.GetString("CharSelectCol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1550.
        /// </summary>
        internal static string CharSelectCol2 {
            get {
                return ResourceManager.GetString("CharSelectCol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 600.
        /// </summary>
        internal static string CharSelectRow0 {
            get {
                return ResourceManager.GetString("CharSelectRow0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 710.
        /// </summary>
        internal static string CharSelectRow1 {
            get {
                return ResourceManager.GetString("CharSelectRow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 825.
        /// </summary>
        internal static string CharSelectRow2 {
            get {
                return ResourceManager.GetString("CharSelectRow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2505,185,30,30.
        /// </summary>
        internal static string Chevron_Region {
            get {
                return ResourceManager.GetString("Chevron_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 450,1025,200,50.
        /// </summary>
        internal static string ClaimAll_Region {
            get {
                return ResourceManager.GetString("ClaimAll_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200,150.
        /// </summary>
        internal static string Clickable_Offset {
            get {
                return ResourceManager.GetString("Clickable_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 425,300,1750,700.
        /// </summary>
        internal static string Clickable_Region {
            get {
                return ResourceManager.GetString("Clickable_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800,400.
        /// </summary>
        internal static string ClickableArea {
            get {
                return ResourceManager.GetString("ClickableArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2460,1225.
        /// </summary>
        internal static string CommunityMenu {
            get {
                return ResourceManager.GetString("CommunityMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300,900,200,75.
        /// </summary>
        internal static string Complete_Region {
            get {
                return ResourceManager.GetString("Complete_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1375,930.
        /// </summary>
        internal static string ConnectButton {
            get {
                return ResourceManager.GetString("ConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1500,1100
        ///1050,250
        ///1225,500.
        /// </summary>
        internal static string ElgaciaShard_Clickpoints {
            get {
                return ResourceManager.GetString("ElgaciaShard_Clickpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2460,1135.
        /// </summary>
        internal static string GameMenu {
            get {
                return ResourceManager.GetString("GameMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1215,700,125,50.
        /// </summary>
        internal static string GoldDonate_Region {
            get {
                return ResourceManager.GetString("GoldDonate_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2400,1225.
        /// </summary>
        internal static string GuideMenu {
            get {
                return ResourceManager.GetString("GuideMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2340,1005.
        /// </summary>
        internal static string GuidePetMenu {
            get {
                return ResourceManager.GetString("GuidePetMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2400,1135.
        /// </summary>
        internal static string GuildMenu {
            get {
                return ResourceManager.GetString("GuildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1130,700.
        /// </summary>
        internal static string GuildNormalSupport {
            get {
                return ResourceManager.GetString("GuildNormalSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1550,600,150,50.
        /// </summary>
        internal static string GuildSupport_Region {
            get {
                return ResourceManager.GetString("GuildSupport_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1280,920,100,50.
        /// </summary>
        internal static string GuildSupportCancel_Region {
            get {
                return ResourceManager.GetString("GuildSupportCancel_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1225,940.
        /// </summary>
        internal static string GuildSupportOk_Button {
            get {
                return ResourceManager.GetString("GuildSupportOk_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 935,1140,250,15.
        /// </summary>
        internal static string HealthBar_Region {
            get {
                return ResourceManager.GetString("HealthBar_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1450,400,530,600.
        /// </summary>
        internal static string Inventory_Region {
            get {
                return ResourceManager.GetString("Inventory_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1105,930.
        /// </summary>
        internal static string Kurzan1640 {
            get {
                return ResourceManager.GetString("Kurzan1640", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1285,820.
        /// </summary>
        internal static string Kurzan1660 {
            get {
                return ResourceManager.GetString("Kurzan1660", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1475,300,500,250.
        /// </summary>
        internal static string KurzanMap1_PreferredArea {
            get {
                return ResourceManager.GetString("KurzanMap1_PreferredArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 550,350
        ///1400,225.
        /// </summary>
        internal static string KurzanMap1_Start {
            get {
                return ResourceManager.GetString("KurzanMap1_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300,625,500,275.
        /// </summary>
        internal static string KurzanMap2_PreferredArea {
            get {
                return ResourceManager.GetString("KurzanMap2_PreferredArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000,250
        ///600,350.
        /// </summary>
        internal static string KurzanMap2_Start {
            get {
                return ResourceManager.GetString("KurzanMap2_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300,400,500,300.
        /// </summary>
        internal static string KurzanMap3_PreferredArea {
            get {
                return ResourceManager.GetString("KurzanMap3_PreferredArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800,250.
        /// </summary>
        internal static string KurzanMap3_Start {
            get {
                return ResourceManager.GetString("KurzanMap3_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1280,180,600,300.
        /// </summary>
        internal static string KurzanMap3_Stickpoint_Region {
            get {
                return ResourceManager.GetString("KurzanMap3_Stickpoint_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2385,350.
        /// </summary>
        internal static string MinimapCenter {
            get {
                return ResourceManager.GetString("MinimapCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2230,220,300,250.
        /// </summary>
        internal static string MinimapRegion {
            get {
                return ResourceManager.GetString("MinimapRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2210,550,150,40.
        /// </summary>
        internal static string OngoingQuest_Region {
            get {
                return ResourceManager.GetString("OngoingQuest_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1715,520.
        /// </summary>
        internal static string PlecciaShard_Clickpoints {
            get {
                return ResourceManager.GetString("PlecciaShard_Clickpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2560.
        /// </summary>
        internal static string ScreenX {
            get {
                return ResourceManager.GetString("ScreenX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1440.
        /// </summary>
        internal static string ScreenY {
            get {
                return ResourceManager.GetString("ScreenY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2525,1220.
        /// </summary>
        internal static string ServicesMenu {
            get {
                return ResourceManager.GetString("ServicesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 950,700,150,50.
        /// </summary>
        internal static string SilverDonate_Region {
            get {
                return ResourceManager.GetString("SilverDonate_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1025,1210,40,40.
        /// </summary>
        internal static string Skill_A {
            get {
                return ResourceManager.GetString("Skill_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1120,1210,40,40.
        /// </summary>
        internal static string Skill_D {
            get {
                return ResourceManager.GetString("Skill_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1100,1162,40,40.
        /// </summary>
        internal static string Skill_E {
            get {
                return ResourceManager.GetString("Skill_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1168,1210,40,40.
        /// </summary>
        internal static string Skill_F {
            get {
                return ResourceManager.GetString("Skill_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 880,1185,40,40.
        /// </summary>
        internal static string Skill_HyperV {
            get {
                return ResourceManager.GetString("Skill_HyperV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1005,1162,40,40.
        /// </summary>
        internal static string Skill_Q {
            get {
                return ResourceManager.GetString("Skill_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1145,1162,40,40.
        /// </summary>
        internal static string Skill_R {
            get {
                return ResourceManager.GetString("Skill_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1075,1210,40,40.
        /// </summary>
        internal static string Skill_S {
            get {
                return ResourceManager.GetString("Skill_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 950,1185,40,40.
        /// </summary>
        internal static string Skill_T {
            get {
                return ResourceManager.GetString("Skill_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 940,1185,40,40.
        /// </summary>
        internal static string Skill_V {
            get {
                return ResourceManager.GetString("Skill_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1050,1162,40,40.
        /// </summary>
        internal static string Skill_W {
            get {
                return ResourceManager.GetString("Skill_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1200,220
        ///375,600.
        /// </summary>
        internal static string SKurzanLeap_Clickpoints {
            get {
                return ResourceManager.GetString("SKurzanLeap_Clickpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 710,930.
        /// </summary>
        internal static string SwitchCharacterButton {
            get {
                return ResourceManager.GetString("SwitchCharacterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250,200,750,150.
        /// </summary>
        internal static string Timeout_Region {
            get {
                return ResourceManager.GetString("Timeout_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 740,335.
        /// </summary>
        internal static string UnaDaily {
            get {
                return ResourceManager.GetString("UnaDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 750,420.
        /// </summary>
        internal static string UnaDailyDropdown {
            get {
                return ResourceManager.GetString("UnaDailyDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 700,540.
        /// </summary>
        internal static string UnaDailyDropdownFavorite {
            get {
                return ResourceManager.GetString("UnaDailyDropdownFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1550,500,100,450.
        /// </summary>
        internal static string UnaDailyRegion {
            get {
                return ResourceManager.GetString("UnaDailyRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400,640
        ///540,1000
        ///850,245
        ///1570,225
        ///1860,350
        ///1890,430
        ///470,1030
        ///500,1100
        ///575,1090
        ///580,285
        ///750,250.
        /// </summary>
        internal static string UnaLopang_Route {
            get {
                return ResourceManager.GetString("UnaLopang_Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2250,1135.
        /// </summary>
        internal static string UnaTask {
            get {
                return ResourceManager.GetString("UnaTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 900,335.
        /// </summary>
        internal static string UnaWeekly {
            get {
                return ResourceManager.GetString("UnaWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800,380.
        /// </summary>
        internal static string UnaWeeklyDropdown {
            get {
                return ResourceManager.GetString("UnaWeeklyDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800,440.
        /// </summary>
        internal static string UnaWeeklyDropdownFavorite {
            get {
                return ResourceManager.GetString("UnaWeeklyDropdownFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1550,470,100,550.
        /// </summary>
        internal static string UnaWeeklyRegion {
            get {
                return ResourceManager.GetString("UnaWeeklyRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1250,220,700,350.
        /// </summary>
        internal static string VoldisLeap_Close {
            get {
                return ResourceManager.GetString("VoldisLeap_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2030,450,150,200.
        /// </summary>
        internal static string VoldisLeap_Npc {
            get {
                return ResourceManager.GetString("VoldisLeap_Npc", resourceCulture);
            }
        }
    }
}
